require:
- rubocop-rspec
AllCops:
  TargetRubyVersion: 2.3
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
Naming/FileName:
  Exclude:
    - lib/yard-sequel.rb
RSpec/ImplicitSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
